# Generated by Django 5.0 on 2024-01-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        default="media/",
                        null=True,
                        upload_to="media/",
                        verbose_name="символ чата",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "about",
                    models.TextField(
                        blank=True, max_length=1500, null=True, verbose_name="о чате"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "чат",
                "verbose_name_plural": "чаты",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
    ]
